In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [12]:
# Load the dataset
df = pd.read_csv("customer.csv")

In [13]:
# Display the first few rows of the DataFrame
print(df.head())

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [14]:
# Select the relevant column for encoding
df1 = df.iloc[:, 2:]  # Adjust this as needed based on your data

In [15]:
# Display the selected data
print(df1.head())

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [16]:
# Initialize LabelEncoder
label = LabelEncoder()

In [18]:
# Apply label encoding to the 'purchase' column
df1['purchase_encoded'] = label.fit_transform(df1['purchased'])

In [20]:

df1

     review education purchased  purchase_encoded
0   Average    School        No                 0
1      Poor        UG        No                 0
2      Good        PG        No                 0
3      Good        PG        No                 0
4   Average        UG        No                 0
5   Average    School       Yes                 1
6      Good    School        No                 0
7      Poor    School       Yes                 1
8   Average        UG        No                 0
9      Good        UG       Yes                 1
10     Good        UG       Yes                 1
11     Good        UG       Yes                 1
12     Poor    School        No                 0
13  Average    School        No                 0
14     Poor        PG       Yes                 1
15     Poor        UG        No                 0
16     Poor        UG       Yes                 1
17     Poor        UG       Yes                 1
18     Good    School        No                 0
19     Poor        PG       Yes                 1
20  Average    School       Yes                 1
21  Average        PG        No                 0
22     Poor        PG       Yes                 1
23     Good    School        No                 0
24  Average        PG       Yes                 1
25     Good    School        No                 0
26     Poor        PG        No                 0
27     Poor        PG        No                 0
28     Poor    School        No                 0
29  Average        UG       Yes                 1
30  Average        UG        No                 0
31     Poor    School       Yes                 1
32  Average        UG       Yes                 1
33     Good        PG       Yes                 1
34  Average    School        No                 0
35     Poor    School       Yes                 1
36     Good        UG       Yes                 1
37  Average        PG       Yes                 1
38     Good    School        No                 0
39     Poor        PG        No                 0
40     Good    School        No                 0
41     Good        PG       Yes                 1
42     Good        PG       Yes                 1
43     Poor        PG        No                 0
44  Average        UG        No                 0
45     Poor        PG       Yes                 1
46     Poor        PG        No                 0
47     Good        PG       Yes                 1
48     Good        UG       Yes                 1
49     Good        UG        No                 0